dependabot-triggers
osisoft/sample-adh-waveform-python pull request #25
Opened 2022-08-09 14:51 UTC by cbardini

2022-08-09 15:41 UTC, jgaughan-aveva approved these changes

2022-08-11 09:00 UTC, anton-dahlin approved these changes

2022-08-11 09:00 UTC, anton-dahlin commented
/azp run

2022-08-11 09:06 UTC, anton-dahlin commented on azure-pipelines.yml
> +    default: ['PYTHON']
There seems to be an issue with the changes related to the ['Python'] here.

From the pipeline 
![image](https://user-images.githubusercontent.com/92155840/184100298-e24ade57-c4c6-4f25-ad45-a8ee7c1f529e.png)

2022-08-11 09:07 UTC, anton-dahlin requested changes
There seems to be an issue with the changes related to the ['Python'] here.

From the pipeline 
![image](https://user-images.githubusercontent.com/92155840/184100298-e24ade57-c4c6-4f25-ad45-a8ee7c1f529e.png)

2022-08-11 09:32 UTC, anton-dahlin commented
> There seems to be an issue with the changes related to the ['Python'] on line 48.
> 
> From the pipeline ![image](https://user-images.githubusercontent.com/92155840/184100298-e24ade57-c4c6-4f25-ad45-a8ee7c1f529e.png)

I found a quote that was missing, it runs now again

2022-08-11 09:32 UTC, anton-dahlin approved these changes

2022-08-11 15:42 UTC, merged